version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /mnt/media/tv:/tv #optional
      - ../Qbittorrent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
